export class ExpedienteBuscar{
  constructor(
      public id_expediente: number,
      public numero: string,
      public DOF: string,
      public EA: string,
      public TA: string,
      public annus: number,
      public aprueba: string,
      public asunto: string,
      public autor: string,
      public cd: number,
      public d_debates: string,
      public desa: number,
      public desch: number,
      public desp_desch: number,
      public ejecutivo: number,
      public enterado: string,
      public entrada: string,
      public fecha_DOF: string,
      public fecha_concluido: string,
      public fechadese: string,
      public id_categoria: number,
      public id_documento: number,
      public id_exp: number,
      public id_gaceta: string,
      public id_mixto: number,
      public legislatura: number,
      public notas: string,
      public observaciones: string,
      public observaprueba: string,
      public periodo: number,
      public refe: string,
      public reforma: number,
      public sinopsis: string,
      public suscritos: string,
      public tipoperiodo: string,
      public turno: string,
      public urgenteyobvia: number,
      public tipoperiodo2?: string,
      public periodo2?: string,
      public annus2?: string,
      public legislatura2?: string,
      public aprueba2?: string,
      public entradaF?: string,
      public apruebaF?: string,
      public fechadeseF?: string,
      public fecha_concluidoF?: string,
      public fecha_DOFF?: string,
      ){}
}

export class Expediente{
  constructor(
      public id_expediente: number,
      public numero: string,
      public docs: {
        DOF: string,
        EA: string,
        TA: string,
        annus: number,
        aprueba: string,
        asunto: string,
        autor: string,
        cd: number,
        d_debates: string,
        desa: number,
        desch: number,
        desp_desch: number,
        ejecutivo: number,
        enterado: string,
        entrada: string,
        fecha_DOF: string,
        fecha_concluido: string,
        fechadese: string,
        id_categoria: number,
        id_documento: number,
        id_exp: number,
        id_gaceta: string,
        id_mixto: number,
        legislatura: number,
        notas: string,
        observaciones: string,
        observaprueba: string,
        periodo: number,
        refe: string,
        reforma: number,
        sinopsis: string,
        suscritos: string,
        tipoperiodo: string,
        turno: string,
        urgenteyobvia: number,
        tipoperiodo2?: string,
        periodo2?: string,
        annus2?: string,
        legislatura2?: string,
        aprueba2?: string,
        entradaF?: string,
        apruebaF?: string,
      },
      ){}
}
 